routes.py
import uuid
from flask import render_template,Blueprint,session,redirect,request,current_app,url_for,flash
import secrets 
from movie_library.forms import movieform,ExtendedMovieform,RegisterForm,LoginForm
from movie_library.models import Movie , User 
from dataclasses import asdict 
import datetime
from passlib.hash import pbkdf2_sha256
pages = Blueprint("pages",__name__, template_folder = "templates", static_folder = "static")
import functools



def login_required(route):
    @functools.wraps(route)
    def route_wrapper(*args, **kwargs):
        if session.get("email") is None:
            return redirect(url_for(".login"))

        return route(*args, **kwargs)

    return route_wrapper


@pages.route('/')
@login_required
def index():
  user_data = current_app.db.user.find_one({"email": session["email"]})
  user = User(**user_data)    #here we are unpacking the data from the database and storing it in a user object
  movie_data = current_app.db.movie.find({"_id": {"$in": user.movies}})
  movies = [Movie(**movie) for movie in movie_data]#here we have used a method to unpack the dictionary data and store it in list elements

  return render_template("index.html",title = "Movies Watchlist",movie_data = movies) # we are passing the movie data to front end


@pages.route("/add", methods = ["GET","POST"])
@login_required

def add():
  form = movieform()

  if form.validate_on_submit():
    movie =  Movie(_id = uuid.uuid4().hex,
              title = form.title.data,
              director = form.director.data,
              year = form.year.data,
    )
    current_app.db.movie.insert_one(asdict(movie))
    current_app.db.user.update_one({"_id": session["user_id"]}, {"$push": {"movies": movie._id}}) #this is done to add the movie to the user list everytime 
    #a movie is created in the user's index page.

  
    return redirect(url_for(".movie", _id=movie._id))


  return render_template("new_movie.html",title = "Add New Movie",form=form )


#last section extended form part

@pages.route("/edit/string/<string:_id>", methods = ["GET","POST"])
@login_required

def edit_movie(_id : str):
  movie = Movie(**current_app.db.movie.find_one({"_id": _id}))
  form = ExtendedMovieform(obj=movie)
  if form.validate_on_submit():
    movie.cast = form.cast.data
    movie.series = form.series.data
    movie.tags = form.tags.data
    movie.description = form.description.data
    movie.video_link = form.video_link.data

    current_app.db.movie.update_one({"_id": _id}, {"$set": asdict(movie)})
    return redirect(url_for(".movie", _id=_id))
  return render_template('movieform.html', movie = movie ,form = form )


#these are the minute updates which we are making to the system to display movie content and all of them are taking in values
#these values are update in the databse and shon again in the front end 
#so that is the reason they take in necessary inputs using pythons datatypes creation.

##all of these functions belong to the same page check the endpoints

@pages.get("/movie/<string:_id>")  #here we are passing the end points from a single page# these can be used to update the existing values in the database.
def movie(_id: str):
    movie = Movie(**current_app.db.movie.find_one({"_id": _id}))
    return render_template("movie_details.html", movie=movie)   #this functionality is added to get the details of the movie from the details pages
#acts more like a get request new concept for a python generator ro fetch data from databse.


@pages.get("/movie/<string:_id>/rate")
@login_required
def rate_movie(_id):
    rating = int(request.args.get("rating"))
    current_app.db.movie.update_one({"_id": _id}, {"$set": {"rating": rating}})

    return redirect(url_for(".movie", _id=_id)) #changed from rate_movie to movie 

@pages.get("/movie/<string:_id>/watch")
@login_required
def watch_today(_id):
  current_app.db.movie.update_one({"_id": _id}, {"$set": {"last_watched": datetime.datetime.today()}})
  
  
  return redirect(url_for(".movie",_id = _id))


@pages.get("/toggle-theme")

def toggle_theme():
  current_theme = session.get("theme")
  if current_theme == "dark":
    session["theme"] = "light"
  else:
    session['theme'] = "dark"
    
  return redirect(request.args.get("current_page")) # this has been done to stay in the same pages


#registration and login part of the application 

@pages.route("/register",methods = ["GET","POST"])

def register():
  if session.get("email"):
    return redirect(url_for(".login"))
  
  form = RegisterForm()

  if form.validate_on_submit():
    user = User(_id = uuid.uuid4().hex,
                email = form.email.data,
                password = pbkdf2_sha256.hash(form.password.data)
    )
    current_app.db.user.insert_one(asdict(user))
    
    flash("You have successfully registered","success")

  return render_template("register.html",title = "movies Watchlist",form=form)

@pages.route("/login",methods = ["GET","POST"])
def login():
  if session.get("email"):
    return redirect(url_for(".index"))   #similar to the above function but we do an error checkiing
  form = LoginForm()

  if form.validate_on_submit():
    user_data = current_app.db.user.find_one({"email": form.email.data})
    if not user_data:
      flash("invalid Usernae/Password Or user doesnt exist",category = "danger")
      return redirect(url_for(".login"))
    
    user = User(**user_data)

    if user and pbkdf2_sha256.verify(form.password.data, user.password):
      session["user_id"] = user._id
      session["email"] = user.email
      flash("You have successfully logged in","success")
      return redirect(url_for(".index"))
    
    flash("invalid Usernae/Password Or user doesnt exist",category = "danger")
    
  return render_template("login.html",title = "movies Watchlist",form=form)
  

  @pages.route("/logout")
  def logout():
    session.clear()
    session["theme"] = current_theme

    return redirect(url_for(".login"))

templates/index.html
{% extends "layout.html" %}

{% block head_content %}
<link rel ="stylesheet" href="{{ url_for('static', filename='movies.css') }}" />
{% endblock %}

{% block main_content %}
    {% if movie_data %}
        <table class="table">
            <colgroup>
                <col style="width: 60%">
                <col style="width: 25%">
                <col style="width: 15%">
            </colgroup>
            <thead>
                <tr class="table__header">
                    <th class="table__cell table__cell--header">Title</th>
                    <th class="table__cell table__cell--header">Release Date</th>
                    <th class="table__cell table__cell--header"></th>
                </tr>
            </thead>
            <tbody>
                {% for movie in movie_data %}
                    <tr>
                        <td class="table__cell">
                            <p class="table__movieTitle">{{ movie.title }}</p>
                            <p class="table__movieDirector">{{ movie.director }}</p>
                        </td>
                        <td class="table__cell">{{ movie.year }}</td>
                        <td class="table__cell"><a href="{{url_for('pages.movie',_id = movie._id)}}" class="table__link">View</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p class="table__empty">You haven't added any movies yet. <a href="{{ url_for('pages.add') }}" class="link">Add one!</a></p>
    {% endif %}
    
    <a href="{{ url_for('pages.add') }}" class="button button--add">
        <span>+</span>
    </a>

{% endblock %}

templates/layout.html
{% from "macros/nav.html" import header %}
{% from "macros/footer.html" import footer %}



<!DOCTYPE html>
<html lang="en" class = "{{'dark-mode' if session.get('theme') == 'dark'}}">
    <head >
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>{{ title | default('Movie Watchlist') }}</title>
        <link href="https://fonts.googleapis.com/css?family=Public+Sans:400,600&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{{ url_for('static', filename='reset.css') }}" />
        <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}" />

        {% block head_content %} {% endblock %}
    </head>
    
    <body>
        {{header(session.get("email"),session.get("theme"))}}
        <main class="main">
            {% block main_content %} {% endblock %}
        </main>
        {{ footer() }}
    </body>
</html>

templates/login.html
{% from "macros/fields.html" import render_text %}

{% extends "layout.html" %}

{% block head_content %}
  <link rel="stylesheet" href="{{ url_for('static', filename='forms.css') }}" />
{% endblock %}

{% block main_content %}
  <form name="login" method="post" novalidate class="form">

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% for category, message in messages %}
        <span class="form__flash form__flash--{{ category }}">{{ message }}</span>
      {% endfor %}
    {% endwith %}

    <div class="form__container">
      {{ form.hidden_tag() }}
      {{ render_text(form.email) }}
      {{ render_text(form.password) }}

      <span class="form__small">
        Don't have an account? <a href="{{url_for('pages.register')}}" class="form__link">Register Here</a>
      </span>
    </div>

    <div>
      {{ form.submit(class="button button--form") }}
    </div>

  </form>
{% endblock %}

templates/movie_details.html
{% from "macros/svgs.html" import star, pencil %}

{% extends "layout.html" %}

{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='movie_details.css') }}" />
{% endblock %}

{% block main_content %}
<div class="container">
    <header class="movie__header">
        <div class="header__row">
            <div class="movie__name">
                <h1>{{ movie.title }}</h1>
                <div class="movie__rating">
                  {% for i in range(5) %}
                  <a class="rating__link" href="{{ url_for('pages.rate_movie', _id=movie._id, rating=i+1) }}">
                      {{ star("star " + ("star--filled" if movie.rating > i else "")) }}
                  </a>
              {% endfor %}
                </div>
            </div>
            <div class="movie__watched">
                {% if movie.last_watched %}
                    <p>
                        Last watched: <a href="{{ url_for('pages.watch_today', _id=movie._id) }}" class="watched__link">
                            <time datetime="{{ movie.last_watched }}">{{movie.last_watched.strftime("%d %b %Y")}}</time>
                        </a>
                    </p>
                {% else %}
                    <p><a href="{{ url_for('pages.watch_today', _id=movie._id) }}" class="watched__link">Not watched yet</a></p>
                {% endif %}
                <a class="movie__edit" href="{{url_for('pages.edit_movie',_id=movie._id)}}">Edit {{ pencil("pencil") }}</a>
            </div>
        </div>
        <div class="header__row">
            <ul class="movie__tags">
            {% for tag in movie.tags %}
                <li class="movie__tag">{{ tag }}</li>
            {% endfor %}
            </ul>
        </div>
    </header>
    {% if movie.video_link %}
    <iframe
        class="movie__video"
        src="{{ movie.video_link }}"
        title="YouTube video player"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen>
    </iframe>
    {% endif %}

    {% if movie.description %}
        <p class="movie__description">{{ movie.description }}</p>
    {% else %}
        <p class="movie__description">No description yet. <a class="link" href="#">Add one?</a></p>
    {% endif %}
    
    <div class="movie__meta">
        {% if movie.cast %}
            <div class="movie__casting">
                <h2>Casting</h2>
                <ul class="list">
                {% for actor in movie.cast %}
                    <li class="list__item">{{ actor }}</li>
                {% endfor %}
                <ul>
            </div>
        {% endif %}
        {% if movie.series | length %}
            <div class="movie__series">
                <h2>Series</h2>
                <ul class="list">
                {% for movie_in_series in movie.series %}
                    <li class="list__item">{{ movie_in_series }}</li>
                {% endfor %}
                <ul>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/movieform.html
{% from "macros/fields.html" import render_text , render_area %}

{%extends "layout.html"%}

{%block head_content%}
<link rel="stylesheet" href="{{ url_for('static', filename='forms.css') }}" />

{% endblock %}


{% block main_content %}
  <form name = "add_movie" method = "post" nonvalidate class="form">
    <div class = "form__container">
      {{form.hidden_tag()}}
      {{render_text(form.title)}}
      {{render_text(form.director)}}
      {{render_text(form.year)}}

      {{render_area(form.cast)}}
      {{render_area(form.series)}}
      {{render_area(form.tags)}}
      {{render_area(form.description)}}
      {{render_text(form.video_link)}}



      </div>
      <div>
        {{form.submit(class_ = "button button--form")}}
      </div>
  </form>

{% endblock %}

templates/new_movie.html
{% from "macros/fields.html" import render_text %}

{%extends "layout.html"%}

{%block head_content%}
<link rel="stylesheet" href="{{ url_for('static', filename='forms.css') }}" />

{% endblock %}


{% block main_content %}
  <form name = "add_movie" method = "post" nonvalidate class="form">
    <div class = "form__container">
      {{form.hidden_tag()}}
      {{render_text(form.title)}}
      {{render_text(form.director)}}
      {{render_text(form.year)}}
      </div>
      <div>
        {{form.submit(class_ = "button button--form")}}
      </div>
  </form>

{% endblock %}

templates/register.html
{% from "macros/fields.html" import render_text %}

{% extends "layout.html" %}

{% block head_content %}
  <link rel="stylesheet" href="{{ url_for('static', filename='forms.css') }}" />
{% endblock %}

{% block main_content %}
  <form name="add_movie" method="post" novalidate class="form">

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% for category, message in messages %}
        <span class="form__flash form__flash--{{ category }}">{{ message }}</span>
      {% endfor %}
    {% endwith %}

    <div class="form__container">
      {{ form.hidden_tag() }}
      {{ render_text(form.email) }}
      {{ render_text(form.password) }}
      {{ render_text(form.confirm_password) }}

      <span class="form__small">
        Already have an account? <a href="{{url_for('pages.login')}}" class="form__link">Log in here</a>
      </span>
    </div>

    <div>
      {{ form.submit(class="button button--form") }}
    </div>

  </form>
{% endblock %}